version: "3"
services:
  harvest-postgres:
    image: postgres:10.3
    restart: always
    container_name: harvest-postgres
    environment:
      POSTGRES_DB: "harvest"
      POSTGRES_USER: "${HARVEST_DB_USER}"
      POSTGRES_PASSWORD: "${HARVEST_DB_PASSWORD}"
    volumes:
      - harvest:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - harvest
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 5

  harvest-api:
    container_name: harvest-api
    image: "harvest-api"
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://${HARVEST_DB_USER}:${HARVEST_DB_PASSWORD}@harvest-postgres:5432/harvest?schema=public"
      TRACTOR_URL: "${TRACTOR_URL}"
      TRACTOR_LOGIN: "${TRACTOR_LOGIN}"
      TRACTOR_PASSWORD: "${TRACTOR_PASSWORD}"
    networks:
      - harvest
    depends_on:
      harvest-postgres:
        condition: service_healthy

  harvest-logs:
    container_name: harvest-logs
    image: fluentd
    networks:
      - harvest
    depends_on:
      - harvest-api
    volumes:
      - ${TRACTOR_LOG_PATH}:/var/log
      - ./config/fluentd.conf:/fluentd/etc/fluent.conf
      - ./config/plugin:/fluentd/plugins
      - ./config/output:/output


volumes:
  harvest:
    name: harvest

networks:
  harvest:
    name: harvest
    driver: bridge
