version: "3"
services:
  harvest-postgres:
    image: postgres:10.3
    restart: always
    container_name: harvest-postgres
    environment:
      POSTGRES_DB: "harvest"
      POSTGRES_USER: "${HARVEST_DB_USER}"
      POSTGRES_PASSWORD: "${HARVEST_DB_PASSWORD}"
    volumes:
      - harvest:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - harvest

  harvest-api:
    container_name: harvest-api
    image: "harvest-api"
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://${HARVEST_DB_USER}:${HARVEST_DB_PASSWORD}@harvest-postgres:5432/harvest?schema=public"
      TRACTOR_URL: "${TRACTOR_URL}"
      TRACTOR_LOGIN: "${TRACTOR_LOGIN}"
      TRACTOR_PASSWORD: "${TRACTOR_PASSWORD}"
    networks:
      - harvest
    depends_on:
      - harvest-postgres

  elasticsearch-setup:
    init: true
    build:
      context: elasticsearch/deploy/
    volumes:
      - elasticsearch-setup:/state:Z
    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD-password}
      KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD-password}
    networks:
      - harvest

  harvest-elasticsearch:
    container_name: harvest-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD-password}
      discovery.type: single-node
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data:z
    networks:
      - harvest

  harvest-kibana:
    container_name: harvest-kibana
    image: docker.elastic.co/kibana/kibana:8.1.0
    ports:
      - "5601:5601"
    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD-password}
      KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD-password}
    networks:
      - harvest
    depends_on:
      - harvest-elasticsearch

volumes:
  harvest:
    name: harvest
  elasticsearch:
    name: elasticsearch
  elasticsearch-setup:
    name: elasticsearch-setup

networks:
  harvest:
    name: harvest
    driver: bridge
